apiVersion: apps/v1
kind: Deployment
metadata:
    name: hello-deployment
spec:
      replicas: 3
      selector:
        matchLabels:
          app: hello
      template:
        metadata:
          labels:
            app: hello
            version: "v2"
        spec:
          containers:
          - name: hello-container
            image: hello-k8s:latest
            imagePullPolicy: Never
            ports:
            - containerPort: 5000

